[project]
name = 'Clarity-Auction-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bid-placement]
path = 'contracts/bid-placement.clar'
clarity_version = 2
epoch = 2.5

[contracts.dispute-resolution]
path = 'contracts/dispute-resolution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
